feat/924 added api for total supply and apy values
UnFederalReserve/unfederalreserve.com pull request #131
Opened 2021-08-09 13:31 UTC by ColtMoney

Was added api for total supply and usdc apy values on home page top section.

2021-08-09 13:45 UTC, vladyslav2 requested changes

2021-08-09 13:45 UTC, vladyslav2 commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
@ColtMoney мне кажется это причина того почему я вижу , а не . 
тут должна быт локаль пользователя а не всегда en-US

2021-08-09 13:46 UTC, OstapL approved these changes

2021-08-09 13:56 UTC, ColtMoney commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
@vladyslav2 если задать явно локаль, то показывает вот так 
![image](https://user-images.githubusercontent.com/15219156/128718057-01ef862b-0d0f-4beb-aceb-3af67b4a2157.png)

2021-08-09 13:58 UTC, ColtMoney commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
@vladyslav2 у тебя как отображается?

2021-08-09 15:35 UTC, vladyslav2 commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
@ColtMoney у меня вот такая проблема https://github.com/UnFederalReserve/development/issues/945 из-за того что не используется моя локаль (тут про дату но проблема такая же https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

2021-08-09 16:47 UTC, ColtMoney commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
@vladyslav2 попробуй проверить у себя вот этот таск ещё раз https://github.com/UnFederalReserve/development/issues/945

2021-08-09 16:48 UTC, ColtMoney commented on src/helpers/utils/common.js
> +const intlCurrency = Intl.NumberFormat('en-US', formatOptions);
там вывод был реализован без явного указания локали en-US, я добавли локаль, то сейчас должно быть норм, но нужно проверить

2021-08-10 09:50 UTC, vladyslav2 approved these changes

2021-08-10 09:50 UTC, merged